import * as XLSX from 'xlsx';
import * as fs from 'fs';
import * as path from 'path';

// Canonical inventory columns mapped to system data model
export const canonicalInventoryColumns = [
  'Asset/Inventory Number',
  'Serial Number',
  'Asset Name',
  'Asset Type',
  'Manufacturer',
  'Model',
  'Status',
  'Location',
  'Company',
  'Department',
  'Assigned Employee Name',
  'Assigned Employee Email',
  'Assigned IT Team',
  'Previous Employee',
  'Assignment Date',
  'Transfer Date',
  'Processor / CPU',
  'RAM (GB)',
  'Storage (GB)',
  'Storage Type',
  'Operating System',
  'MAC Address',
  'IP Address',
  'Purchase Date',
  'Purchase Cost (USD)',
  'Warranty Expiry Date',
  'Notes',
];

const sampleData = [
  {
    'Asset/Inventory Number': 'AST-ENG-409',
    'Serial Number': 'C02G89A1MD6R',
    'Asset Name': 'MacBook Pro 16" (M3 Max)',
    'Asset Type': 'LAPTOP',
    'Manufacturer': 'Apple',
    'Model': 'MacBook Pro 16-inch Nov 2023',
    'Status': 'Active',
    'Location': 'San Francisco Tech Hub',
    'Company': 'Accurate Group',
    'Department': 'Software Engineering & DevOps',
    'Assigned Employee Name': 'Rahul Sharma',
    'Assigned Employee Email': 'rahul@accurategroup.com',
    'Assigned IT Team': 'Tier 1 Service Desk & User Support',
    'Previous Employee': 'David Chen',
    'Assignment Date': '2024-01-15',
    'Transfer Date': '2024-06-01',
    'Processor / CPU': 'Apple M3 Max 16-core',
    'RAM (GB)': 36,
    'Storage (GB)': 1000,
    'Storage Type': 'NVMe SSD',
    'Operating System': 'macOS Sonoma 14.6',
    'MAC Address': '3C:22:FB:91:AA:12',
    'IP Address': '10.0.14.88',
    'Purchase Date': '2024-01-15',
    'Purchase Cost (USD)': 3499,
    'Warranty Expiry Date': '2027-01-15',
    'Notes': 'High-performance engineering build laptop.',
  },
  {
    'Asset/Inventory Number': 'AST-IT-102',
    'Serial Number': '5CD32189PL',
    'Asset Name': 'ThinkPad X1 Carbon Gen 11',
    'Asset Type': 'LAPTOP',
    'Manufacturer': 'Lenovo',
    'Model': 'ThinkPad X1 Carbon Gen 11',
    'Status': 'Active',
    'Location': 'New York Global HQ',
    'Company': 'Accurate Group',
    'Department': 'Information Technology & Security',
    'Assigned Employee Name': 'Sarah Jenkins',
    'Assigned Employee Email': 'itadmin@accurategroup.com',
    'Assigned IT Team': 'Tier 1 Service Desk & User Support',
    'Previous Employee': '',
    'Assignment Date': '2023-08-10',
    'Transfer Date': '',
    'Processor / CPU': 'Intel Core i7-1365U',
    'RAM (GB)': 32,
    'Storage (GB)': 1000,
    'Storage Type': 'NVMe SSD',
    'Operating System': 'Windows 11 Enterprise',
    'MAC Address': 'E8:6A:64:1B:99:43',
    'IP Address': '10.0.2.45',
    'Purchase Date': '2023-08-10',
    'Purchase Cost (USD)': 2150,
    'Warranty Expiry Date': '2026-08-10',
    'Notes': 'IT Administration primary terminal.',
  },
  {
    'Asset/Inventory Number': 'AST-TECH-204',
    'Serial Number': 'DLX8902KJ1',
    'Asset Name': 'Dell Latitude 7440',
    'Asset Type': 'LAPTOP',
    'Manufacturer': 'Dell',
    'Model': 'Latitude 7440 Enterprise',
    'Status': 'Active',
    'Location': 'San Francisco Tech Hub',
    'Company': 'Accurate Group',
    'Department': 'Information Technology & Security',
    'Assigned Employee Name': 'Marcus Vance',
    'Assigned Employee Email': 'technician@accurategroup.com',
    'Assigned IT Team': 'Tier 1 Service Desk & User Support',
    'Previous Employee': '',
    'Assignment Date': '2023-11-20',
    'Transfer Date': '',
    'Processor / CPU': 'Intel Core i7-1370P',
    'RAM (GB)': 32,
    'Storage (GB)': 512,
    'Storage Type': 'NVMe SSD',
    'Operating System': 'Ubuntu Linux 24.04 LTS',
    'MAC Address': 'B4:2E:99:81:CD:77',
    'IP Address': '10.0.14.92',
    'Purchase Date': '2023-11-20',
    'Purchase Cost (USD)': 1850,
    'Warranty Expiry Date': '2026-11-20',
    'Notes': 'IT Support technician mobile diagnostic kit.',
  },
  {
    'Asset/Inventory Number': 'AST-FIN-112',
    'Serial Number': '5CD49811TR',
    'Asset Name': 'HP Elite Dragonfly G4',
    'Asset Type': 'LAPTOP',
    'Manufacturer': 'HP',
    'Model': 'Elite Dragonfly G4',
    'Status': 'Active',
    'Location': 'New York Global HQ',
    'Company': 'Accurate Group',
    'Department': 'Finance & Accounting',
    'Assigned Employee Name': 'Ananya Patel',
    'Assigned Employee Email': 'ananya@accurategroup.com',
    'Assigned IT Team': 'Tier 1 Service Desk & User Support',
    'Previous Employee': '',
    'Assignment Date': '2024-03-01',
    'Transfer Date': '',
    'Processor / CPU': 'Intel Core i7-1355U',
    'RAM (GB)': 16,
    'Storage (GB)': 512,
    'Storage Type': 'NVMe SSD',
    'Operating System': 'Windows 11 Enterprise',
    'MAC Address': 'A0:B1:C2:D3:E4:F5',
    'IP Address': '10.0.2.89',
    'Purchase Date': '2024-03-01',
    'Purchase Cost (USD)': 2200,
    'Warranty Expiry Date': '2027-03-01',
    'Notes': 'Finance auditing & payroll workstation.',
  },
  {
    'Asset/Inventory Number': 'AST-POOL-018',
    'Serial Number': 'C02FK081MD6T',
    'Asset Name': 'MacBook Air 15" (M2) Ready Pool',
    'Asset Type': 'LAPTOP',
    'Manufacturer': 'Apple',
    'Model': 'MacBook Air 15-inch 2023',
    'Status': 'Inactive',
    'Location': 'New York Global HQ',
    'Company': 'Accurate Group',
    'Department': 'Information Technology & Security',
    'Assigned Employee Name': '',
    'Assigned Employee Email': '',
    'Assigned IT Team': 'Tier 1 Service Desk & User Support',
    'Previous Employee': 'Michael Chang',
    'Assignment Date': '',
    'Transfer Date': '2024-07-15',
    'Processor / CPU': 'Apple M2 8-core',
    'RAM (GB)': 16,
    'Storage (GB)': 512,
    'Storage Type': 'SSD',
    'Operating System': 'macOS Sonoma',
    'MAC Address': '70:EF:00:23:44:91',
    'IP Address': '',
    'Purchase Date': '2024-02-14',
    'Purchase Cost (USD)': 1499,
    'Warranty Expiry Date': '2027-02-14',
    'Notes': 'Ready-pool standby unit for incoming new hires.',
  },
  {
    'Asset/Inventory Number': 'AST-DEV-550',
    'Serial Number': '8CC99120KL',
    'Asset Name': 'Dell Precision 5860 Tower Workstation',
    'Asset Type': 'WORKSTATION',
    'Manufacturer': 'Dell',
    'Model': 'Precision 5860 Tower',
    'Status': 'Under Repair',
    'Location': 'San Francisco Tech Hub',
    'Company': 'Accurate Group',
    'Department': 'Software Engineering & DevOps',
    'Assigned Employee Name': '',
    'Assigned Employee Email': '',
    'Assigned IT Team': 'Tier 1 Service Desk & User Support',
    'Previous Employee': 'Alex Rivera',
    'Assignment Date': '',
    'Transfer Date': '2024-08-10',
    'Processor / CPU': 'Intel Xeon W5-2465X',
    'RAM (GB)': 64,
    'Storage (GB)': 2000,
    'Storage Type': 'NVMe SSD',
    'Operating System': 'Ubuntu Linux 24.04 LTS',
    'MAC Address': '18:66:DA:22:90:31',
    'IP Address': '',
    'Purchase Date': '2023-09-10',
    'Purchase Cost (USD)': 4200,
    'Warranty Expiry Date': '2026-09-10',
    'Notes': 'Under repair: Power supply fan failure undergoing OEM warranty replacement.',
  },
  {
    'Asset/Inventory Number': 'AST-LEG-099',
    'Serial Number': '4XJ901289Z',
    'Asset Name': 'Lenovo ThinkPad T480s (Legacy)',
    'Asset Type': 'LAPTOP',
    'Manufacturer': 'Lenovo',
    'Model': 'ThinkPad T480s',
    'Status': 'Retired',
    'Location': 'New York Global HQ',
    'Company': 'Accurate Group',
    'Department': 'Global Operations & Facilities',
    'Assigned Employee Name': '',
    'Assigned Employee Email': '',
    'Assigned IT Team': 'Tier 1 Service Desk & User Support',
    'Previous Employee': 'Robert King',
    'Assignment Date': '',
    'Transfer Date': '2024-05-12',
    'Processor / CPU': 'Intel Core i5-8350U',
    'RAM (GB)': 16,
    'Storage (GB)': 256,
    'Storage Type': 'SSD',
    'Operating System': 'Windows 10 Pro',
    'MAC Address': '00:2B:67:88:1A:0F',
    'IP Address': '',
    'Purchase Date': '2019-04-18',
    'Purchase Cost (USD)': 1350,
    'Warranty Expiry Date': '2022-04-18',
    'Notes': 'Decommissioned / Retired after 5-year corporate lifecycle. Preserved for inventory audit.',
  },
  {
    'Asset/Inventory Number': 'AST-DESK-301',
    'Serial Number': 'MJ089901KA',
    'Asset Name': 'HP Z2 Mini G9 Desktop Workstation',
    'Asset Type': 'DESKTOP',
    'Manufacturer': 'HP',
    'Model': 'Z2 Mini G9',
    'Status': 'Active',
    'Location': 'London European Operations',
    'Company': 'Accurate Group',
    'Department': 'Global Operations & Facilities',
    'Assigned Employee Name': 'Vikram Malhotra',
    'Assigned Employee Email': 'vikram@accurategroup.com',
    'Assigned IT Team': 'Infrastructure & Network Systems',
    'Previous Employee': '',
    'Assignment Date': '2024-02-01',
    'Transfer Date': '',
    'Processor / CPU': 'Intel Core i9-13900K',
    'RAM (GB)': 64,
    'Storage (GB)': 1000,
    'Storage Type': 'NVMe SSD',
    'Operating System': 'Windows 11 Enterprise',
    'MAC Address': '94:C6:91:02:44:88',
    'IP Address': '10.0.8.112',
    'Purchase Date': '2024-01-20',
    'Purchase Cost (USD)': 2850,
    'Warranty Expiry Date': '2027-01-20',
    'Notes': 'Compact desktop dedicated for operational dashboard monitoring.',
  },
  {
    'Asset/Inventory Number': 'AST-NET-551',
    'Serial Number': 'FOC2438V09A',
    'Asset Name': 'Cisco Catalyst 9300 48-Port PoE Switch',
    'Asset Type': 'NETWORK_DEVICE',
    'Manufacturer': 'Cisco Systems',
    'Model': 'C9300-48P-A',
    'Status': 'Active',
    'Location': 'London European Operations',
    'Company': 'Accurate Group',
    'Department': 'Information Technology & Security',
    'Assigned Employee Name': '',
    'Assigned Employee Email': '',
    'Assigned IT Team': 'Infrastructure & Network Systems',
    'Previous Employee': '',
    'Assignment Date': '',
    'Transfer Date': '',
    'Processor / CPU': 'x86 4-core',
    'RAM (GB)': 16,
    'Storage (GB)': 16,
    'Storage Type': 'Flash',
    'Operating System': 'Cisco IOS-XE 17.9',
    'MAC Address': '74:86:7A:31:09:BB',
    'IP Address': '10.0.8.1',
    'Purchase Date': '2023-05-18',
    'Purchase Cost (USD)': 5400,
    'Warranty Expiry Date': '2028-05-18',
    'Notes': 'Main rack switch for London operations center.',
  },
  {
    'Asset/Inventory Number': 'AST-SEC-901',
    'Serial Number': 'PAN-PA-3260-91',
    'Asset Name': 'Palo Alto PA-3260 Next-Gen Firewall',
    'Asset Type': 'NETWORK_DEVICE',
    'Manufacturer': 'Palo Alto Networks',
    'Model': 'PA-3260',
    'Status': 'Active',
    'Location': 'New York Global HQ',
    'Company': 'Accurate Group',
    'Department': 'Information Technology & Security',
    'Assigned Employee Name': '',
    'Assigned Employee Email': '',
    'Assigned IT Team': 'Information Security & Access Management',
    'Previous Employee': '',
    'Assignment Date': '',
    'Transfer Date': '',
    'Processor / CPU': 'PAN-OS ASIC multi-core',
    'RAM (GB)': 32,
    'Storage (GB)': 120,
    'Storage Type': 'SSD',
    'Operating System': 'PAN-OS 11.1',
    'MAC Address': '00:1B:17:89:FE:23',
    'IP Address': '10.0.0.1',
    'Purchase Date': '2023-04-12',
    'Purchase Cost (USD)': 12500,
    'Warranty Expiry Date': '2028-04-12',
    'Notes': 'Enterprise edge security gateway.',
  },
];

export function generateInventoryWorkbook(): Buffer {
  const wb = XLSX.utils.book_new();
  const ws = XLSX.utils.json_to_sheet(sampleData, { header: canonicalInventoryColumns });

  // Set column widths
  const colWidths = canonicalInventoryColumns.map((col) => ({
    wch: Math.max(col.length + 4, 18),
  }));
  ws['!cols'] = colWidths;

  XLSX.utils.book_append_sheet(wb, ws, 'IT Computer Inventory');
  return XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' });
}

// Generate the files
const publicDir = path.resolve(process.cwd(), 'public');
const uploadsDir = path.resolve(process.cwd(), 'uploads');

if (!fs.existsSync(publicDir)) fs.mkdirSync(publicDir, { recursive: true });
if (!fs.existsSync(uploadsDir)) fs.mkdirSync(uploadsDir, { recursive: true });

const buffer = generateInventoryWorkbook();
fs.writeFileSync(path.join(publicDir, 'organization_inventory_workbook.xlsx'), buffer);
fs.writeFileSync(path.join(uploadsDir, 'organization_inventory_workbook.xlsx'), buffer);

console.log('Successfully generated organization_inventory_workbook.xlsx in public/ and uploads/');
